version: "3.9"

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
