output   = "./adapters/repositories/models"
wipe     = true
no-tests = true

[psql]
  dbname = "products_service"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode = "disable"
  blacklist = ["migrations"]
