apiVersion: apps/v1
kind: Deployment

metadata:
  name: bff
  labels:
    app: bff

spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: lucasmls/bff:latest
        ports:
        - containerPort: 8080
